BACK PROPAGATION USING PYTORCH

y=(x^n)
dy/dx = n*(x^(n-1))

Step 1: Forward Propagation (Making Predictions)

Input Data: You start with input data — like an image, text, or numbers.

Passing Through the Network: The data goes through each layer of the neural network.

Weighted Sum: In each neuron (node), inputs are multiplied by weights and then added together with a bias.

Activation Function: This sum passes through an activation function (like ReLU or sigmoid) to add non-linearity.

Output: Eventually, the data reaches the output layer, which produces predictions (like class probabilities or numeric values).

Step 2: Calculate Error

Loss Function: Compare the network’s prediction to the true answer using a loss function (e.g., mean squared error or cross-entropy).

Error Value: This gives a number representing how “wrong” the prediction is.

Step 3: Backward Propagation (Learning from Mistakes)

Calculate Gradients: The network calculates how much each weight and bias contributed to the error using calculus (specifically, derivatives).

Chain Rule: It applies the chain rule to find gradients layer by layer, moving backward from the output towards the input.

Step 4: Update Weights

Adjust Weights and Biases: Using the gradients, the network updates weights and biases to reduce error (usually with an optimization method like Gradient Descent).

Repeat: This process (forward pass, error calculation, backward pass, weight update) repeats many times with different data until the model learns well.

In [1]:
import torch

In [2]:
x=torch.tensor(4.0,requires_grad=True)    #Basically says that gradient should be intialised

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y=x**2

In [5]:
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
# Back propagartion ==> y=2*x
y.backward()      #Computes the gradient of the current tensor


In [7]:
print(x.grad)

tensor(8.)


In [ ]:
#Assume as Neural network flow

In [ ]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]    #Floating point numbers only
torch_input=torch.tensor(lst,requires_grad=True)   #X 

In [9]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [ ]:
#Example function (y=x**3+x**2)
## derivative=3x**2+2x
y=torch_input**3+torch_input**2 #Y

In [11]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [12]:
#Output of layer=Z
z=y.sum()

In [13]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [14]:
z.backward()

In [16]:
#Now backpropagartion
torch_input.grad   #Applies derivative directly


tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

In [ ]:
#We can calculate loss and then do  other steps now