In [1]:
import torch

In [2]:
torch.__version__

'2.7.1+cpu'

In [3]:
import numpy as np

In [4]:
lst=[3,4,5,6]
arr=np.array(lst)

In [7]:
arr

array([3, 4, 5, 6])

In [5]:
arr.dtype

dtype('int64')

NUMPY ARRAY TO PYTORCH TENSORS

In [6]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [8]:
# Indexing is similar to numpy
tensors[:2]

tensor([3, 4])

In [10]:
tensors[1:4]

tensor([4, 5, 6])

In [12]:
#Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [13]:
tensors

tensor([  3,   4,   5, 100])

In [14]:
arr

array([  3,   4,   5, 100])

In [15]:
# Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [16]:
tensor_arr[3]=20

In [17]:
tensor_arr

tensor([ 3,  4,  5, 20])

In [18]:
arr

array([  3,   4,   5, 100])

In [19]:
#zeroes and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [20]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

ARITHMETIC OPERATIONS

In [ ]:
#These operations are performed in mathematical calculations of neural networks 

In [21]:
a=torch.tensor([3,4,5],dtype=torch.float)
b=torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [22]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [29]:
# To store in another variable c
c=torch.zeros(3)

In [30]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [31]:
c

tensor([ 7.,  9., 11.])

In [ ]:
#Some more operations

#tensor[7,9,11]
torch.add(a,b).sum()

tensor(27.)

In [24]:
A=torch.tensor(np.arange(0,15).reshape(5,3))

In [25]:
A

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [26]:
A[:,0]

tensor([ 0,  3,  6,  9, 12])

In [28]:
A[:,0:3]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [33]:
#Dot product and multiplication operations
x=torch.tensor([3,4,5],dtype=torch.float)
y=torch.tensor([4,5,6],dtype=torch.float)

In [34]:
x.mul(y)

tensor([12., 20., 30.])

In [ ]:
# 3*4 + 4*5 + 5*6

In [35]:
x.dot(y)

tensor(62.)

In [ ]:
## Matrix Multiplication

In [36]:
x=torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y=torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [37]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [38]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [39]:
x@y

tensor([[55., 53.],
        [90., 92.]])